backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webpush/', include('webpush.urls')),
    path('device/', include(('device.urls', 'device'), namespace='device')),
    path('', include(('user.urls', 'user'), namespace='user')),
    path('', TemplateView.as_view(template_name='base/home.html'), name='home')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/device/urls.py
from django.urls import path

from device.views import DeviceIndexView, DeviceSyncCodeView, DeviceUpdateView

urlpatterns = [
    path('edit/<pk>/', DeviceUpdateView.as_view(), name='update'),
    path('sync/', DeviceSyncCodeView.as_view(), name='sync'),
    path('', DeviceIndexView.as_view(), name='index'),
]

backend/user/urls.py
from django.urls import path

from user.views import LogoutView, SignupView, LoginView

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login')
]

backend/device/models.py
from django.contrib.auth import get_user_model
from django.core import validators
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _, ugettext

from device.constants import NOTIFICATION_TYPE_UP, NOTIFICATION_TYPE_LEFT, NOTIFICATION_TYPE_DOWN, \
    NOTIFICATION_TYPE_RIGHT, NOTIFICATION_TYPE_UP_LEFT, NOTIFICATION_TYPE_UP_RIGHT, NOTIFICATION_TYPE_TEMP_HIGH, \
    NOTIFICATION_TYPE_TEMP_LOW, NOTIFICATION_TYPE_LIGHT, NOTIFICATION_TYPE_OFF
from device.managers import DeviceSyncCodeManager

User = get_user_model()


class DeviceBaseModel(models.Model):
    """
        Modelo Basico que incluye los campos para la fecha de creacion y la fecha de modificacion
    """
    created = models.DateTimeField(
        verbose_name=_('Created date'),
        auto_now_add=True,
    )
    last_modified = models.DateTimeField(
        verbose_name=_('Last Modified date'),
        auto_now=True,
    )

    class Meta:
        abstract = True


class Device(DeviceBaseModel):
    """
        Modelo del dispositivo
    """
    identifier = models.CharField(
        db_index=True,
        verbose_name=_('Device ID'),
        max_length=20,
        unique=True
    )
    name = models.CharField(
        verbose_name=_('Name'),
        max_length=255,
        default='Asistente Digital'
    )
    owners = models.ManyToManyField(
        verbose_name=_('Owners'),
        related_name='devices',
        to=User,
        blank=True
    )
    joystick_up = models.CharField(
        verbose_name=_('Joystick Up'),
        max_length=20,
        default='',
        blank=True
    )
    joystick_left = models.CharField(
        verbose_name=_('Joystick left'),
        max_length=20,
        default='',
        blank=True
    )
    joystick_down = models.CharField(
        verbose_name=_('Joystick Down'),
        max_length=20,
        default='',
        blank=True
    )
    joystick_right = models.CharField(
        verbose_name=_('Joystick Right'),
        max_length=20,
        default='',
        blank=True
    )
    joystick_up_left = models.CharField(
        verbose_name=_('Joystick Up-Left'),
        max_length=20,
        default='',
        blank=True
    )
    joystick_up_right = models.CharField(
        verbose_name=_('Joystick Up-Right'),
        max_length=20,
        default='',
        blank=True
    )
    joystick_down = models.CharField(
        verbose_name=_('Joystick Down'),
        max_length=20,
        default='Cancelar',
    )
    min_temperature = models.PositiveSmallIntegerField(
        verbose_name=_('Min Temperature'),
        validators=[
            validators.MinValueValidator(1),
            validators.MaxValueValidator(40)
        ],
        null=True,
        blank=True
    )
    max_temperature = models.PositiveSmallIntegerField(
        verbose_name=_('Max Temperature'),
        validators=[
            validators.MinValueValidator(1),
            validators.MaxValueValidator(40)
        ],
        null=True,
        blank=True
    )
    is_night_mode_enabled = models.BooleanField(
        verbose_name=_('Night Mode Enabled'),
        default=False
    )
    is_device_on = models.BooleanField(
        verbose_name=_('Night Mode Enabled'),
        default=False
    )
    last_seen_at = models.DateTimeField(
        verbose_name=_('Last Seen At'),
        null=True,
        blank=True
    )
    wifi_ssid = models.CharField(
        verbose_name=_('Wi-Fi SSID'),
        max_length=32,
        blank=True,
        null=True
    )
    wifi_password = models.CharField(
        verbose_name=_('Wi-Fi Password'),
        max_length=63,
        blank=True,
        null=True
    )
    night_mode_start = models.TimeField(
        verbose_name=_('Night Mode Start At'),
        null=True,
        blank=True
    )
    night_mode_end = models.TimeField(
        verbose_name=_('Night Mode End At'),
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('name', 'created')
        verbose_name = _('Device')
        verbose_name_plural = _('Devices')

    def __str__(self):
        return f'{self.name} ({self.identifier})'

    def get_notification_message(self, notification_type):
        messages = {
            NOTIFICATION_TYPE_UP: self.joystick_up or '',
            NOTIFICATION_TYPE_LEFT: self.joystick_left or '',
            NOTIFICATION_TYPE_DOWN: self.joystick_down or '',
            NOTIFICATION_TYPE_RIGHT: self.joystick_right or '',
            NOTIFICATION_TYPE_UP_LEFT: self.joystick_up_left or '',
            NOTIFICATION_TYPE_UP_RIGHT: self.joystick_up_right or '',
            NOTIFICATION_TYPE_TEMP_HIGH: f'{ugettext("La temperatura es superior a")} {self.max_temperature} ºC',
            NOTIFICATION_TYPE_TEMP_LOW: f'{ugettext("La temperatura es inferior a")} {self.min_temperature} ºC',
            NOTIFICATION_TYPE_LIGHT: ugettext('Se ha encendido una luz'),
            NOTIFICATION_TYPE_OFF: ugettext('El dispositivo puede estar apagado')
        }
        return messages[notification_type]

    def set_device_on(self):
        self.is_device_on = True
        self.last_seen_at = timezone.now()
        self.save()


class DeviceSyncCode(DeviceBaseModel):
    """
        Modelo del codigo de sincronizacion
    """
    device = models.ForeignKey(
        verbose_name=_('Device'),
        to=Device,
        on_delete=models.CASCADE,
    )
    sync_code = models.CharField(
        db_index=True,
        verbose_name=_('Sync Code'),
        max_length=9,
        unique=True
    )
    used = models.BooleanField(
        verbose_name=_('Used'),
        default=False
    )
    used_by = models.ForeignKey(
        verbose_name=_('Used by'),
        to=User,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

    objects = DeviceSyncCodeManager()

    class Meta:
        ordering = ('-created', )
        verbose_name = _('Device Sync Code')
        verbose_name_plural = _('Device Sync Codes')

    def __str__(self):
        return f'{self.sync_code} ({self.device}). Used: {self.used}'

    def use(self, user):
        """
        Utiliza un codigo de sincronizacion
        :param user: Usuario que utiliza el codigo
        :return: None
        """
        # Anyadimos el usuario a los duenyos del dispositivo
        self.device.owners.add(user)
        # Marcamos el codigo como usado e indicamos quien lo ha usado
        self.used = True
        self.used_by = user
        # Guardamos los cambios
        self.save()

backend/device/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _, ugettext
from device.models import DeviceSyncCode, Device


class DeviceSyncCodeForm(forms.Form):
    """
        Formulario para la vista de sincronizacion
    """
    sync_code = forms.CharField(
        max_length=9,
        required=True
    )

    class Meta:
        fields = ('sync_code', )

    def clean_sync_code(self):
        value = self.cleaned_data['sync_code']
        # comprobamos si existe un codigo que no esté utilizado y que el valor sea el introducido
        exists = DeviceSyncCode.objects.filter(
            sync_code=value,
            used=False
        ).exists()
        if not exists:
            raise forms.ValidationError(_('El código no es válido'))
        return value


class DeviceForm(forms.ModelForm):
    """
        Formulario para la vista de configuracion de un dispositivo
    """
    class Meta:
        fields = (
            'name', 'joystick_up', 'joystick_left', 'joystick_down', 'joystick_right', 'joystick_up_left',
            'joystick_up_right', 'joystick_down', 'min_temperature', 'max_temperature', 'is_night_mode_enabled',
            'wifi_ssid', 'wifi_password', 'night_mode_start', 'night_mode_end'
        )
        model = Device

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['wifi_password'].widget.input_type = 'password'
        self.fields['night_mode_start'].widget.input_type = 'time'
        self.fields['night_mode_end'].widget.input_type = 'time'

    def clean(self):
        errors = {}
        if self.cleaned_data.get('min_temperature') is not None and self.cleaned_data.get('max_temperature') \
                is not None and self.cleaned_data['min_temperature'] > self.cleaned_data['max_temperature']:
            errors['max_temperature'] = [forms.ValidationError(
                _("Min temperature can't be higher than max temperature"), code='invalid_temp'
            )]

        wifi_ssid = self.cleaned_data.get('wifi_ssid')
        wifi_pass = self.cleaned_data.get('wifi_password')

        if (not wifi_ssid and wifi_pass) or (wifi_ssid and not wifi_pass):
            errors['wifi_password'] = [forms.ValidationError(
                _('Wi-Fi Configuration must be either full or blank'), code='invalid_wifi'
            )]
        if errors:
            raise forms.ValidationError(errors)
        return self.cleaned_data

backend/device/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.utils.translation import ugettext
from django.views.generic import TemplateView, FormView, UpdateView

from base.mixins import LoginRequiredMixin
from device.forms import DeviceSyncCodeForm, DeviceForm
from device.models import DeviceSyncCode
from mqtt.publish import mqtt_publish_conf


class DeviceAlertMixin:

    def add_alert(self, msg, is_error=False):
        self.request.session['alert'] = {
            'msg': msg,
            'is_error': is_error
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['alert'] = self.request.session.pop('alert', None)
        return context


class DeviceIndexView(DeviceAlertMixin, LoginRequiredMixin, TemplateView):
    """
        Vista principal del dashboard. Requiere login
    """
    template_name = 'device/index.html'

    def get_context_data(self, **kwargs):
        # Recuperamos los dispositivos del usuario y los anyadimos al contexto de la vista
        context = super().get_context_data(**kwargs)
        context['devices'] = self.request.user.devices.all()
        return context


class DeviceSyncCodeView(DeviceAlertMixin, LoginRequiredMixin, FormView):
    """
        Vista para utilizar un codigo de sincronizacion y vincular un dispositivo
    """
    form_class = DeviceSyncCodeForm
    template_name = 'device/sync.html'

    def form_valid(self, form):
        # Recuperamos el codigo de la base de datos
        sync_code = DeviceSyncCode.objects.get(
            sync_code=form.cleaned_data['sync_code']
        )
        # Lo utilizamos
        sync_code.use(self.request.user)
        self.add_alert(ugettext('Su dispositivo se ha sincronizado correctamente'))
        return HttpResponseRedirect(reverse('device:update', args=(sync_code.device.pk, )))

    def form_invalid(self, form):
        self.add_alert(ugettext('El código no es válido'), is_error=True)
        return super().form_invalid(form)


class DeviceUpdateView(DeviceAlertMixin, LoginRequiredMixin, UpdateView):
    """
        Vista para modificar un dispositivo y configurarlo
    """
    form_class = DeviceForm
    success_url = reverse_lazy('device:index')
    template_name = 'device/update.html'

    def get_queryset(self):
        # Recuperamos solo los dispostivos del usuario
        return self.request.user.devices.all()

    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['original'] = self.get_object()
            return context

    def form_valid(self, form):
        # Publicamos la nueva configuracion
        ret = super().form_valid(form)
        mqtt_publish_conf(self.get_object())
        self.add_alert(ugettext('Sus cambios se han guardado correctamente'))
        return ret

    def form_invalid(self, form):
        self.add_alert(ugettext('La configuración es incorrecta. Por favor, corrija los errores'), is_error=True)
        return super().form_invalid(form)

backend/device/templates/device/index.html
{% extends "device/layout.html" %}

{% load i18n static %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'device/device_index.css' %}">
{% endblock %}

{% block device_content %}
    <div class="device-title">
        <h2>{% trans "Mis Dispositivos" %}</h2>
        <div class="device-title__cta">
            <a class="pure-button button-icon button-primary" href="{% url "device:sync" %}">
                <i class="button-icon__icon button-icon__icon--text">
                    +
                </i>
                <span>{% trans "Sincronizar Dispositivo" %}</span>
            </a>
        </div>
    </div>

    <div class="device-list">
        {% for device in devices %}
            <div class="device">
                <i class="device__status {% if device.is_device_on %}device__status--online{% endif %}" title="{% if device.is_device_on %}{% trans "Conectado" %}{% else %}{% trans "Desconectado" %}{% endif %}"></i>
                <div class="device-content">
                    <div class="device-content__name">
                        <p class="device__title">{{ device.name }}</p>
                        <p class="device__last-seen hide-for-mobile hide-for-tablet-only">{% trans "Última vez" %}: <span>{{ device.last_seen_at|default:'-' }}</span></p>
                    </div>
                    <div class="device-content__data-container">
                        <div class="device-content__data">
                            <p>{% trans "Temp Min" %}</p>
                            <span>{{ device.min_temperature|default:'-' }} ºC</span>
                        </div>
                        <div class="device-content__data">
                            <p>{% trans "Temp Max" %}</p>
                            <span>{{ device.max_temperature|default:'-' }} ºC</span>
                        </div>
                        <div class="device-content__data device-content__data--night">
                            <p>{% trans "Modo Noche" %}</p>
                            <span {% if device.is_night_mode_enabled %}class="night-mode-enabled"{% endif %}>{% if device.is_night_mode_enabled %}{% trans "Activo" %}{% else %}{% trans "Inactivo" %}{% endif %}</span>
                        </div>
                    </div>
                    <div class="device-content__cta"><a class="pure-button button-primary" href="{% url 'device:update' device.pk %}">{% trans "Configurar" %}</a></div>

                </div>

            </div>
        {% endfor %}
    </div>
{% endblock %}

backend/device/templates/device/layout.html
{% extends "base/base.html" %}

{% load i18n static webpush_notifications %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'device/layout.css' %}">
    {% webpush_header %}
{% endblock %}

{% block content %}
    <div id="enable-notif-wall" class="notif-wall notif-wall--hidden">
        <button class="notif-wall__close" onclick="closeWall('enable-notif-wall')">
            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
        </button>
        <div class="notif-wall__message">
            <p class="notif-wall__title">{% trans "¡Activa las Notificaciones!" %}</p>
            <p class="notif-wall__subtitle">{% trans "Así podrás recibir mensajes del Asistente Digital en este dispositivo" %}.</p>
        </div>
    </div>
    <div id="invalid-browser-wall" class="notif-wall notif-wall--hidden">
        <button class="notif-wall__close" onclick="closeWall('invalid-browser-wall')">
            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
        </button>
        <div class="notif-wall__message">
            <p class="notif-wall__title">{% trans "¡Este navegador no es válido!" %}</p>
            <p class="notif-wall__subtitle">{% trans "Este navegador no puede recibir notificaciones. Por favor, usa un navegador como Chrome, Firefox o Edge" %}.</p>
        </div>
    </div>
    <div id="notification-blocked-wall" class="notif-wall notif-wall--hidden">
        <button class="notif-wall__close" onclick="closeWall('notification-blocked-wall')">
            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
        </button>
        <div class="notif-wall__message">
            <p class="notif-wall__title">{% trans "¡Las notificaciones están bloqueadas!" %}</p>
            <p class="notif-wall__subtitle">{% trans "Por favor, habilita las notificaciones en el navegador y recarga la página" %}.</p>
        </div>
    </div>
    <main class="device-layout">
        <div class="device-menu-container">
            <div class="container device-menu">
                <menu class="device-menu hide-for-mobile">
                    <p><a href="{% url "device:index" %}">{% trans "Mis Dispositivos" %}</a></p>
                </menu>
                <div class="device-menu__notf">
                    <button class="pure-button button-icon button-alt button-notification" id="webpush-notification-button">
                        <i class="button-icon__icon button-notification__icon button-notification__icon--enable">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path><path d="M13.73 21a2 2 0 0 1-3.46 0"></path></svg>
                        </i>
                        <i class="button-icon__icon button-notification__icon button-notification__icon--disable">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell-off"><path d="M13.73 21a2 2 0 0 1-3.46 0"></path><path d="M18.63 13A17.89 17.89 0 0 1 18 8"></path><path d="M6.26 6.26A5.86 5.86 0 0 0 6 8c0 7-3 9-3 9h14"></path><path d="M18 8a6 6 0 0 0-9.33-5"></path><line x1="1" y1="1" x2="23" y2="23"></line></svg>
                        </i>
                        <span class="button-notification__text button-notification__text--enable">{% trans "Activar Notificaciones" %}</span>
                        <span class="button-notification__text button-notification__text--disable">{% trans "Desactivar Notificaciones" %}</span>
                    </button>
                    <span id="invalid-browser-msg" class="error-msg" style="display: none"><strong>{% trans "¡Este navegador no es válido!" %}</strong></span>
                    <span id="notification-blocked-msg" class="error-msg" style="display: none"><strong>{% trans "¡Las notificaciones están bloqueadas!" %}</strong></span>
                </div>
            </div>
        </div>

        <article class="content container">
            {% block device_content %}
            {% endblock %}
        </article>
    </main>
    {% if alert %}
    <div id="alert" class="alert {% if alert.is_error %}alert--error{% endif %}">
        {{ alert.msg }}
    </div>
    {% endif %}
{% endblock %}

{% block js %}
    <script>
        /*
            Alert handler
         */
        document.addEventListener('DOMContentLoaded', function () {
            const alert = document.getElementById('alert')

            if (!!alert) {
                alert.classList.add('alert--visible');

                setTimeout(function() {
                    alert.classList.remove('alert--visible')
                }, 3000);
            }
        })
    </script>
{% endblock %}

backend/device/templates/device/sync.html
{% extends "device/layout.html" %}

{% load i18n static %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'device/forms.css' %}">
{% endblock %}


{% block device_content %}
    <p style="margin-bottom: 1rem"><a href="{% url 'device:index' %}" >< {% trans "Volver a Mis Dispositivos" %}</a></p>
    <h2>{% trans "Sincronizar Dispositivo" %}</h2>
    <form method="post" class="pure-form pure-form-stacked">
        {% csrf_token %}
        <div class="form-box">
            <h3 class="form-box__title">{% trans "Código de Sincronización" %}</h3>
            <label for="{{ form.sync_code.id_for_label }}"></label>
            {{ form.sync_code }}
            <span class="pure-form-message">{% trans "Introduzca el código que se muestra en la pantalla del dispositivo" %}.</span>
            {% if form.sync_code.errors.0 %}
                <span class="pure-form-message error-msg">{{ form.sync_code.errors.0 }}</span>
            {% endif %}
        </div>
        <p class="form-submit">
            <button type="submit" class="pure-button button-primary">
                {% trans "Sincronizar Dispositivo" %}
            </button>
        </p>
    </form>
{% endblock %}