backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webpush/', include('webpush.urls')),
    path('device/', include(('device.urls', 'device'), namespace='device')),
    path('', include(('user.urls', 'user'), namespace='user')),
    path('', TemplateView.as_view(template_name='base/home.html'), name='home')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/device/urls.py
from django.urls import path

from device.views import DeviceIndexView, DeviceSyncCodeView, DeviceUpdateView

urlpatterns = [
    path('edit/<pk>/', DeviceUpdateView.as_view(), name='update'),
    path('sync/', DeviceSyncCodeView.as_view(), name='sync'),
    path('', DeviceIndexView.as_view(), name='index'),
]

backend/user/urls.py
from django.urls import path

from user.views import LogoutView, SignupView, LoginView

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login')
]

backend/base/models.py
from django.db import models

# Create your models here.

backend/base/views.py
from django.shortcuts import render

# Create your views here.

backend/base/templates/base/base.html
{% load static i18n %}

<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block meta_title %}Asistente Digital para Personas Dependientes{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}Asistente Digital para Personas Dependientes. Comunicación inmediata entre cuidador y paciente con solo mover un dedo.{% endblock %}">
    <meta name="author" content="Alejandro Diaz">

    {% comment %}RESPONSIVE{% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% comment %}Favicon{% endcomment %}
    <link rel="apple-touch-icon" sizes="180x180" href="{%  static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{%  static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{%  static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{%  static 'favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{%  static 'favicon/safari-pinned-tab.svg" color="#5bbad5' %}">
    <link rel="shortcut icon" href="{%  static 'favicon/favicon.ico' %}">
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="msapplication-config" content="{%  static 'favicon/browserconfig.xml' %}">
    <meta name="theme-color" content="#2d89ef">

    {% comment %}Pure CSS{% endcomment %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.3/build/pure-min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'common.css' %}">
    {% block extra_head  %}
    {% endblock %}

</head>

<body>
    {% block header %}
        <header class="header">
            <div class="container header__content">
                <a class="header__title" href="{% url 'home' %}">ADpd</a>
                <div class="header__menu">
                    <div class="hamburger hamburger--spin hide-for-tablet" role="button" id="hamburger">
                        <div class="hamburger-box">
                          <div class="hamburger-inner"></div>
                        </div>
                      </div>
                    {% if not user.is_authenticated or True %}
                        <ul class="header-menu show-mobile" id="header-menu">
                            {% if not user.is_authenticated %}
                                <li><a href="{% url 'user:login' %}">{% trans "Acceder a mi cuenta" %}</a></li>
                                <li><a class="pure-button button-primary" href="{% url 'user:signup' %}">{% trans "Crear una cuenta" %}</a></li>
                            {% else %}
                                <li><a href="{% url 'user:logout' %}">{% trans "Cerrar Sesión" %}</a></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </header>
    {% endblock %}
    {% block content %}
    {% endblock %}
    <script>
        var hamburgerButton = document.getElementById('hamburger');
        var headerMenu = document.getElementById('header-menu');

        hamburgerButton.addEventListener('click', function(event) {
           hamburgerButton.classList.toggle('is-active');
           headerMenu.classList.toggle('header-menu--mb-visible')
        });
    </script>
    {% block js %}
    {% endblock %}
</body>
</html>

backend/base/templates/base/home.html
{% extends "base/base.html" %}

{% load i18n static %}

{% block extra_head %}
      <link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
    <main>
        <div class="hero" style="background-image: url({% static 'img/home_bg.jpg' %})">
            <div class="hero__cover"></div>
            <div class="hero__content container">
                <div class="hero__title">
                    <h1>{% trans "Asistente Digital para Personas Dependientes" %}</h1>
                    <p class="fs-lg mt-lg mb-sm">
                        {% blocktrans %}
                            Comunicación inmediata entre cuidador y paciente.
                        {% endblocktrans %}
                    </p>
                    <p class="f-italic">
                        {% blocktrans %}
                            Sin escribir. Sin usar la voz. Con solo un dedo.
                        {% endblocktrans %}
                    </p>
                </div>
                <div class="hero__subtitle">
                    {% if not user.is_authenticated %}
                        <a class="pure-button button-primary" href="{% url 'user:signup' %}">{% trans "Crear una Cuenta" %}</a>
                        <a class="pure-button button-primary" href="{% url 'user:login' %}">{% trans "Acceder a mi Cuenta" %}</a>
                    {% else %}
                        <a class="pure-button button-primary" href="{% url 'device:index' %}">{% trans "Ver Mis Dispositivos" %}</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="section section--notf">
            <div class="container section__content">
                <div class="section__text">
                    <h2>{% trans "Comunicación con solo mover un dedo" %}</h2>
                    <p class="mt-md">
                        {% blocktrans %}
                           Notificar al cuidador es tan sencillo como mover un joystick. Se pueden configurar hasta 6 mensajes diferentes que variarán según la notificación.
                        {% endblocktrans %}
                    </p>
                </div>
                <div class="section__img section__img--notf">
                    <img class="pure-img" src="{% static "img/mano_dispositivo.png" %}" alt="">
                </div>
            </div>
        </div>
        <div class="section section--app">
            <div class="container section__content">
                <div class="section__img section__img--app">
                    <img class="pure-img" src="{% static "img/app.png" %}" alt="">
                </div>
                <div class="section__text">
                    <h2>{% trans "Sin Instalar Nada" %}</h2>
                    <p class="mt-md">
                        {% blocktrans %}
                            Recibe notificaciones en cualquier dispositivo, ya sea un ordenador o un smartphone.
                            El Asistente Digital tan solo necesita que tengas instalado un navegador compatible como Chrome, Edge, o Firefox.
                        {% endblocktrans %}
                    </p>
                </div>
            </div>
        </div>
        <div class="section section--temp">
            <div class="container section__content">
                <div class="section__text">
                    <h2>{% trans "Controla la temperatura y la luz" %}</h2>
                    <p class="mt-md">
                        {% blocktrans %}
                            El Asistente Digital notificará si la temperatura de la habitación es inadecuada. Además,
                            permite activar un modo nocturno para que, si se detecta una luz encendida, se avise al cuidador.
                        {% endblocktrans %}
                    </p>
                </div>
                <div class="section__img section__img--temp">
                    <img class="pure-img" src="{% static "img/temp_luz.png" %}" alt="">
                </div>
            </div>
        </div>
    </main>
    <footer class="footer">
        <h2>Empieza a utilizar tu Asistente Digital</h2>
        <div class="footer__buttons">
            {% if not user.is_authenticated %}
                <a class="pure-button button-primary" href="{% url 'user:signup' %}">{% trans "Crear una Cuenta" %}</a>
                <a class="pure-button button-primary" href="{% url 'user:login' %}">{% trans "Acceder a mi Cuenta" %}</a>
            {% else %}
                <a class="pure-button button-primary" href="{% url 'device:index' %}">{% trans "Ver Mis Dispositivos" %}</a>
            {% endif %}
        </div>

        <p class="copyright">Asistente Digital Para Personas Dependientes es un Trabajo de Fin de Grado en el área de Sistema Empotrados para la Universitat Oberta de Catalunya.</p>
        <p><small>&copy; Copyright 2020, <a href="mailto:alediaper2@uoc.edu">Alejandro Díaz</a></small></p>

    </footer>
{% endblock %}